NAME = megaphone

SRC = megaphone.cpp

FLAGS = -Wall -Wextra -Werror -std=c++98

CC = c++	
all : $(NAME)

$(NAME) : $(SRC) 
	@$(CC) $(FLAGS) $(SRC) -o $(NAME)

clean :
	@rm -rf $(NAME)

fclean :

re :
